In [1]:
import pandas as pd

df = pd.read_csv('winequality-red.csv', sep=';')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [2]:
from sklearn.model_selection import train_test_split

X, y = df.iloc[:, :-1], df['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=0)
X_train.shape

(1279, 11)

In [3]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

models = {'DT': DecisionTreeClassifier(random_state=0), 
          'bagging': BaggingClassifier(DecisionTreeClassifier(), n_estimators=10, 
                                       max_samples=1., max_features=1., n_jobs=-1, random_state=0)}
scores = {}
for name, clf in models.items():
    clf.fit(X_train, y_train)
    scores[(name, 'Train score')] = clf.score(X_train, y_train)
    scores[(name, 'Test score')] = clf.score(X_test, y_test)
pd.Series(scores).unstack()

         Test score  Train score
DT         0.693750     1.000000
bagging    0.721875     0.982799